# Generated by Django 3.2.22 on 2023-11-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20231125_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(choices=[('article', 'Article'), ('blog', 'Blog'), ('podcast', 'Podcast')], related_name='posts', to='journal.Category'),
        ),
    ]
