# Generated by Django 3.2.22 on 2023-11-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20231120_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_reason',
            field=models.CharField(choices=[('general_query', 'General Query'), ('glasses', 'Glasses'), ('sunglasses', 'Sunglasses'), ('technical_issue', 'Technical Issue'), ('other', 'Other')], default='general_query', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
