# Generated by Django 3.2.22 on 2023-11-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_type', models.CharField(choices=[('Glasses', 'Glasses'), ('Sunglasses', 'Sunglasses')], max_length=50)),
                ('body_text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
