# Generated by Django 3.2.22 on 2023-10-30 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('brand', models.CharField(max_length=254)),
                ('sku', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=400)),
                ('colour', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Glasses', 'Glasses'), ('Sunglasses', 'Sunglasses')], max_length=50)),
                ('material', models.CharField(choices=[('Acetate', 'Acetate'), ('Metal', 'Metal'), ('Titanium', 'Titanium')], max_length=50)),
                ('shape', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
